<?php

return array (
	'mode' => '"exact"',
	'theme' => '"advanced"',
	'plugins' => '"safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,inlinepopups"',
	'theme_advanced_buttons1' => '"newdocument,|,cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,sub,sup"',
	'theme_advanced_buttons2' => '"styleselect,formatselect,fontselect,fontsizeselect,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,forecolor,backcolor"',
	'theme_advanced_buttons3' => '"tablecontrols,|,hr,removeformat,visualaid,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen"',
	'theme_advanced_buttons4' => '"insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,|,insertdate,inserttime,preview"',
	'theme_advanced_toolbar_location' => '"top"',
	'theme_advanced_toolbar_align' => '"left"',
	'theme_advanced_statusbar_location' => '"bottom"',
	'theme_advanced_resizing' => 'true',
	'theme_advanced_resize_horizontal' => 'false',
	'theme_advanced_resizing_use_cookie' => 'true',
	'accessibility_warnings' => 'false',
	//'paste_auto_cleanup_on_paste' => 'true',
	'plugin_insertdate_dateFormat' => '"%d.%m.%Y"',
	'plugin_insertdate_timeFormat' => '"%H:%M:%S"',
	'valid_elements' => '"*[*]"',
	'extended_valid_elements' => '"*[*],noindex[*]"',
	'file_browser_callback' => '"HostCMSFileManager.fileBrowserCallBack"',
	'paste_insert_word_content_callback' => '"convertWord"',
	'media_strict' => 'false',
	'convert_urls' => 'false',
	'relative_urls' => 'false',
	'remove_script_host' => 'false',
	//'forced_root_block' => '""',
	'cleanup' => 'false',
	'entity_encoding' => '""',
	'verify_html' => 'false',
	'valid_children' => '"+body[style]"',
	//'height'=>'500',
);